package uz.vosiq.edugames.utils;
import java.util.*;
public class LanguageManager {
    private static String lang = "uz";
    private static final Map<String, Map<String, String>> T = new HashMap<>();
    static {
        Map<String,String> uz=new HashMap<>(),ru=new HashMap<>(),en=new HashMap<>();
        String[][] data = {
            {"app.title","Vosiq International School","Восик Интернэшнл Скул","Vosiq International School"},
            {"app.subtitle","O'yin orqali o'rganish platformasi","Платформа обучения через игры","Learn Through Play Platform"},
            {"menu.home","Bosh sahifa","Главная","Home"},
            {"menu.games","O'yinlar","Игры","Games"},
            {"menu.subjects","Fanlar","Предметы","Subjects"},
            {"menu.about","Ilova haqida","О приложении","About App"},
            {"btn.play","O'ynash","Играть","Play"},
            {"btn.back","Orqaga","Назад","Back"},
            {"btn.start","Boshlash","Начать","Start"},
            {"btn.retry","Qayta urinish","Повторить","Try Again"},
            {"quiz.question","Savol","Вопрос","Question"},
            {"quiz.score","Ball","Очки","Score"},
            {"quiz.time","Vaqt","Время","Time"},
            {"quiz.correct","To'g'ri! ✓","Правильно! ✓","Correct! ✓"},
            {"quiz.wrong","Noto'g'ri! ✗","Неправильно! ✗","Wrong! ✗"},
            {"quiz.result","Natija","Результат","Result"},
            {"quiz.outof","dan","из","out of"},
            {"subject.math","Matematika","Математика","Mathematics"},
            {"subject.english","Ingliz tili","Английский язык","English"},
            {"subject.russian","Rus tili","Русский язык","Russian"},
            {"subject.uzbek","O'zbek tili","Узбекский язык","Uzbek"},
            {"subject.biology","Biologiya","Биология","Biology"},
            {"subject.chemistry","Kimyo","Химия","Chemistry"},
            {"subject.physics","Fizika","Физика","Physics"},
            {"subject.history","Tarix","История","History"},
            {"subject.geo","Geografiya","География","Geography"},
            {"subject.it","Informatika","Информатика","Informatics"},
            {"subject.math.desc","Hisoblash mahoratini oshiring","Улучшайте навыки вычислений","Improve calculation skills"},
            {"subject.english.desc","So'z va grammatika","Слова и грамматика","Words and grammar"},
            {"subject.russian.desc","Grammatika va lug'at","Грамматика и словарь","Grammar and vocabulary"},
            {"subject.uzbek.desc","Imlo va uslub","Орфография и стиль","Spelling and style"},
            {"subject.biology.desc","Tirik tabiat","Живая природа","Living nature"},
            {"subject.chemistry.desc","Elementlar va formulalar","Элементы и формулы","Elements and formulas"},
            {"subject.physics.desc","Qonunlar va formulalar","Законы и формулы","Laws and formulas"},
            {"subject.history.desc","Tarixiy voqealar","Исторические события","Historical events"},
            {"subject.geo.desc","Xaritalar va mamlakatlar","Карты и страны","Maps and countries"},
            {"subject.it.desc","Dasturlash asoslari","Основы программирования","Programming basics"},
            {"game.quiz","Viktorina","Викторина","Quiz"},
            {"game.memory","Xotira o'yini","Игра памяти","Memory Game"},
            {"game.truefalse","To'g'ri / Noto'g'ri","Верно / Неверно","True / False"},
            {"game.quiz.desc","Savollar javob bering va ball to'plang","Отвечайте на вопросы и набирайте очки","Answer questions and collect points"},
            {"game.memory.desc","Kartochkalarni yodlab, juftlarini toping","Запоминайте карточки и находите пары","Memorize cards and find pairs"},
            {"game.truefalse.desc","Bayonot to'g'rimi yoki noto'g'rimi?","Утверждение верно или неверно?","Is the statement true or false?"},
            {"about.title","Ilova haqida","О приложении","About the App"},
            {"welcome.title","Xush kelibsiz!","Добро пожаловать!","Welcome!"},
            {"welcome.subtitle","Ta'limiy o'yinlar orqali bilimingizni oshiring","Улучшайте знания через образовательные игры","Improve your knowledge through educational games"},
            {"select.subject","Fan tanlang","Выберите предмет","Select Subject"},
            {"select.game","O'yin turini tanlang","Выберите тип игры","Select Game Type"},
            {"highscore","Eng yuqori ball","Лучший результат","High Score"},
            {"level.easy","Oson","Лёгкий","Easy"},
            {"level.medium","O'rta","Средний","Medium"},
            {"level.hard","Qiyin","Сложный","Hard"},
            {"select.level","Qiyinlik darajasini tanlang","Выберите уровень сложности","Select Difficulty"},
            {"about.appname","Vosiq EduGames","Vosiq EduGames","Vosiq EduGames"},
            {"about.school.val","Vosiq International School","Vosiq International School","Vosiq International School"},
            {"about.author.val","Najmiddinov Sirojiddin","Наджмиддинов Сирожиддин","Najmiddinov Sirojiddin"},
            {"about.class.val","9A sinf o'quvchisi","Ученик 9A класса","9A grade student"},
            {"about.version.val","1.0.0","1.0.0","1.0.0"},
            {"about.year.val","2025","2025","2025"},
            {"about.author.label","Yaratuvchi","Создатель","Developer"},
            {"about.school.label","Maktab","Школа","School"},
            {"about.class.label","Sinf","Класс","Class"},
            {"about.version.label","Versiya","Версия","Version"},
            {"about.year.label","Yil","Год","Year"},
            {"about.app.label","Ilova nomi","Название","App Name"},            {"menu_exit","Chiqish","Выйти","Exit"},
            {"lang_uz","O'zbek","Узбекский","Uzbek"},
            {"lang_ru","Русский","Русский","Russian"},
            {"lang_en","English","Английский","English"},
            {"choose_subject","Fan tanlang","Выберите предмет","Select Subject"},
            {"select_game_type","O'yin turini tanlang","Тип игры","Game Type"},
            {"start","Boshlash","Начать","Start"},
            {"back","Orqaga","Назад","Back"},
            {"quiz_title","Viktorina","Викторина","Quiz"},
            {"memory_title","Xotira o'yini","Игра памяти","Memory Game"},
            {"truefalse_title","To'g'ri / Noto'g'ri","Верно / Неверно","True / False"},
            {"question","Savol","Вопрос","Question"},
            {"score","Ball","Очки","Score"},
            {"time","Vaqt","Время","Time"},
            {"correct","To'g'ri! ✓","Правильно! ✓","Correct! ✓"},
            {"wrong","Noto'g'ri! ✗","Неправильно! ✗","Wrong! ✗"},
            {"result_title","Natija","Результат","Result"},
            {"play_again","Qayta o'ynash","Играть снова","Play Again"},
            {"main_menu","Bosh menyu","Главное меню","Main Menu"},
            {"pairs_found","Juftlar topildi","Пар найдено","Pairs Found"},
            {"math","Matematika","Математика","Mathematics"},
            {"english","Ingliz tili","Английский","English"},
            {"uzbek","O'zbek tili","Узбекский","Uzbek"},
            {"russian","Rus tili","Русский","Russian"},
            {"biology","Biologiya","Биология","Biology"},
            {"chemistry","Kimyo","Химия","Chemistry"},
            {"physics","Fizika","Физика","Physics"},
            {"history","Tarix","История","History"},
            {"geography","Geografiya","География","Geography"},
            {"informatics","Informatika","Информатика","Informatics"},            {"game_over","O'yin tugadi!","Игра окончена!","Game Over!"},
            {"your_score","Sizning ballingiz","Ваши очки","Your Score"},
            {"congrats","Ajoyib! Tabriklaymiz","Поздравляем!","Congratulations!"},
            {"try_harder","Ko'proq harakat qiling","Старайтесь больше","Try harder"},
            {"true_btn","✓  TO'G'RI","✓  ВЕРНО","✓  TRUE"},
            {"false_btn","✗  NOTO'G'RI","✗  НЕВЕРНО","✗  FALSE"},
        };
        for(String[] row : data){
            uz.put(row[0],row[1]); ru.put(row[0],row[2]); en.put(row[0],row[3]);
        }
        T.put("uz",uz); T.put("ru",ru); T.put("en",en);
    }
    public static void setLanguage(String l){ lang=l; }
    public static String getLang(){ return lang; }
    public static String get(String key){
        Map<String,String> m=T.get(lang);
        if(m!=null&&m.containsKey(key))return m.get(key);
        return T.getOrDefault("uz",new HashMap<>()).getOrDefault(key,key);
    }
}
